/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ConcurrencyTestRouteImport } from './routes/concurrency-test'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ApprovalHistoryRouteImport } from './routes/approval-history'
import { Route as IndexRouteImport } from './routes/index'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrencyTestRoute = ConcurrencyTestRouteImport.update({
  id: '/concurrency-test',
  path: '/concurrency-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalHistoryRoute = ApprovalHistoryRouteImport.update({
  id: '/approval-history',
  path: '/approval-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-history': typeof ApprovalHistoryRoute
  '/challenges': typeof ChallengesRoute
  '/concurrency-test': typeof ConcurrencyTestRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-history': typeof ApprovalHistoryRoute
  '/challenges': typeof ChallengesRoute
  '/concurrency-test': typeof ConcurrencyTestRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-history': typeof ApprovalHistoryRoute
  '/challenges': typeof ChallengesRoute
  '/concurrency-test': typeof ConcurrencyTestRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-history'
    | '/challenges'
    | '/concurrency-test'
    | '/orders'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-history'
    | '/challenges'
    | '/concurrency-test'
    | '/orders'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/approval-history'
    | '/challenges'
    | '/concurrency-test'
    | '/orders'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalHistoryRoute: typeof ApprovalHistoryRoute
  ChallengesRoute: typeof ChallengesRoute
  ConcurrencyTestRoute: typeof ConcurrencyTestRoute
  OrdersRoute: typeof OrdersRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrency-test': {
      id: '/concurrency-test'
      path: '/concurrency-test'
      fullPath: '/concurrency-test'
      preLoaderRoute: typeof ConcurrencyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-history': {
      id: '/approval-history'
      path: '/approval-history'
      fullPath: '/approval-history'
      preLoaderRoute: typeof ApprovalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalHistoryRoute: ApprovalHistoryRoute,
  ChallengesRoute: ChallengesRoute,
  ConcurrencyTestRoute: ConcurrencyTestRoute,
  OrdersRoute: OrdersRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
